### ISSUE TITLE
Re-eval approch

### ISSUE THREAD

**Issue by dfontana** [dfontana/lyra-parent#5]
Daemonize relies on `os::unix`, which makes using this in Windows near impossible; furthermore a lot of low level custom code is being written. It might be worth re-evaluating Tauri's readiness/if it's simplified itself enough to get something rapidly put together. The key, current pain points include:

- Tray. It looks like tray is getting close to stable ("few weeks" as of [20 days ago](https://github.com/tauri-apps/tauri/issues/1818)). The [Beta API exists today though](https://github.com/tauri-apps/tauri/commit/c0909270216983bed47453ddf5902abf5082fe42) and it looks like [Wry is ready to go](https://github.com/tauri-apps/wry/blob/dev/examples/system_tray.rs)
- Global Hotkeys. These are tricky to implement and maintain, and not necessarily something that matters from the overall app POV. 
- Window Management. As new use cases onboard (Config window, etc), a lot of time is gonna go into framework code rather than feature code.

Exploring the [Tauri Bridge pattern](https://tauri.studio/en/docs/usage/patterns/bridge) may ease this; albeit the first attempts at this found it wasn't straight forward enough/worth it

**Comment by dfontana** [comment]
Attempted on branch tauri https://github.com/dfontana/lyra-parent/tree/tauri ; it doesn't look to be any more simplified than before frankly. In #6 I was able to drop daemonize, since we don't really need a background process if we have the ability to launch as system tray. The app will still show as open on the dock which is less than ideal (ideally it just launches to the taskbar and that's that). As TAO/WRY expand functionality in this domain, it might end up not needing tauri.

Global hotkeys are a similar story, see related issue.

**Comment by lemarier** [comment]
You should check https://github.com/tauri-apps/wry/blob/feat/tao-examples/examples/system_tray.rs#L53

Also global hotkey are in this example

**Comment by dfontana** [comment]
@lemarier Thank you so much for the heads up!! This was wicked useful -- just put up a PR trying out those features (Global hotkeys + system tray only). They look to be doing _just the trick_, which saves me a ton of extra overhead :) I'll have to test it out on my windows machine tomorrow

**Comment by dfontana** [comment]
Hey @lemarier (sorry for the second ping!) - I did spot a regression it looks like, I made a little 'report' here on how I produced it https://github.com/dfontana/lyra-parent/pull/11

It looks like the focus issue that was on WRY back in May. I wonder if it has anything to do with [these changes made to TAO](https://github.com/tauri-apps/tao/compare/afd1316a7e0289ec34fb49f12ccfb5e3c1387b7b..d1065e3d9e4f0f48b366ce9736a57b5866c003db#diff-4803bb2335a17d700335730b9f62828e001faa602b9b894dff572422c737b78aR476-R481), specifically surrounding the `is_minimized` check? FWIW I'm on MacOS Big Sur 11.1 (20C69)

**Comment by lemarier** [comment]
> I did spot a regression it looks like

thanks, a lot, i'll look into it
